/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.1
 * Generated at: 2024-06-22 17:44:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MenuPrincipal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1687997712759L));
    _jspx_dependants.put("jar:file:/C:/Users/X/Desktop/PROYECTO%20FINAL%20-%20LP2/Proyecto-LP2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Proyecto-SistemaTallerCursos1.3/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153403082000L));
    _jspx_dependants.put("/template/menu.jsp", Long.valueOf(1687997712774L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Menu - Taller de cursos de verano</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light bg-info\">\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("    <ul class=\"navbar-nav mr-auto\">\r\n");
      out.write("      <li class=\"nav-item active\">\r\n");
      out.write("        <a style=\"margin-left: 10px; border: none\" class=\"btn btn-outline-light\" href=\"#\"><i class=\"fas fa-home\"></i> Home <span class=\"sr-only\">(current)</span></a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a style=\"margin-left: 10px; border: none\" class=\"btn btn-outline-light\" href=\"#\" role=\"button\" data-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("          <i class=\"fas fa-book\"></i> Cursos\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\">\r\n");
      out.write("          <!-- <a class=\"dropdown-item btn btn-hover\" href=\"FrmRegistrarCurso.jsp\"><i class=\"fas fa-address-book\"></i> Registrar Cursos</a> -->\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"ControladorCurso?accion=Listado\"><i class=\"fas fa-list\"></i> Listado Cursos</a>\r\n");
      out.write("          <!-- <a class=\"dropdown-item\" href=\"AsignarCurso.jsp\"><i class=\"fas fa-folder-plus\"></i> Asignar Cursos</a> -->\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"ControladorAsignatura?accion=Listado\"><i class=\"fas fa-list\"></i> Lista Cursos Asignados</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a style=\"margin-left: 10px; border: none\" class=\"btn btn-outline-light\" href=\"#\" role=\"button\" data-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("          <i class=\"fas fa-user-tie\"></i> Docentes\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\">\r\n");
      out.write("          <!-- <a class=\"dropdown-item\" href=\"FrmRegistrarDocente.jsp\"><i class=\"fas fa-user-plus\"></i> Registrar Docentes</a> -->\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"ControladorDocente?accion=Listado\"><i class=\"fas fa-list\"></i> Listado Docentes</a>\r\n");
      out.write("         \r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a style=\"margin-left: 10px; border: none\" class=\"btn btn-outline-light\" href=\"#\" role=\"button\" data-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("          <i class=\"fas fa-users\"></i> Estudiantes\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\">\r\n");
      out.write("          <!-- <a class=\"dropdown-item\" href=\"FrmRegistrarEstudiante.jsp\"><i class=\"fas fa-user-plus\"></i> Registrar Estudiantes</a> -->\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"ControladorEstudiante?accion=Listado\"><i class=\"fas fa-list\"></i> Listado Estudiantes</a>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a style=\"margin-left: 10px; border: none\" class=\"btn btn-outline-light\" href=\"#\" role=\"button\" data-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("          <i class=\"fas fa-address-card\"></i> Inscripcion\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-menu\">\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"ControladorInscripcion?accion=Listado\"><i class=\"fab fa-readme\"></i> Listado para Inscripcion</a>\r\n");
      out.write("          <a class=\"dropdown-item\" href=\"ControladorInscripcion?accion=ListadoInscrito\"><i class=\"fas fa-list\"></i> Listado Inscripciones</a>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("    </ul>\r\n");
      out.write("   <a href=\"Index.jsp\" id=\"cerrarSesionBtn\" class=\"btn btn-danger\"><i class=\"fas fa-sign-out-alt\"></i> Cerrar Sesion</a>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  document.getElementById(\"cerrarSesionBtn\").addEventListener(\"click\", function(event) {\r\n");
      out.write("    event.preventDefault(); // Evita que se realice la acciÃ³n predeterminada del enlace\r\n");
      out.write("\r\n");
      out.write("    // Muestra una ventana de confirmaciÃ³n\r\n");
      out.write("    Swal.fire({\r\n");
      out.write("      title: 'Confirmacion',\r\n");
      out.write("      text: 'Estas seguro de cerrar sesion?',\r\n");
      out.write("      icon: 'question',\r\n");
      out.write("      showCancelButton: true,\r\n");
      out.write("      confirmButtonColor: '#3085d6',\r\n");
      out.write("      cancelButtonColor: '#d33',\r\n");
      out.write("      confirmButtonText: 'Si, cerrar sesion',\r\n");
      out.write("      cancelButtonText: 'Cancelar'\r\n");
      out.write("    }).then((result) => {\r\n");
      out.write("      if (result.isConfirmed) {\r\n");
      out.write("        // Redirige al usuario a la pÃ¡gina de cierre de sesiÃ³n\r\n");
      out.write("        window.location.href = \"Index.jsp\";\r\n");
      out.write("      }\r\n");
      out.write("    });\r\n");
      out.write("  });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mensaje}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("<h3>Bienvenido al Sistema</h3><h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${verusu.getNomusuario()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("</div>\r\n");
      out.write('\r');
      out.write('\n');
 if (request.getAttribute("successMessage") != null && !request.getAttribute("successMessage").toString().isEmpty()) { 
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        Swal.fire({\r\n");
      out.write("            title: 'Éxito',\r\n");
      out.write("            text: '");
      out.print( request.getAttribute("successMessage").toString() );
      out.write("',\r\n");
      out.write("            icon: 'success',\r\n");
      out.write("            confirmButtonColor: '#3085d6',\r\n");
      out.write("            confirmButtonText: 'Aceptar'\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
